### ISSUE TITLE
Specify preferred audio input

### ISSUE THREAD

**Issue by benfrancis** [mozilla/androidspeech#13]
I'd really like to be able to specify a preferred audio input so that I can use a microphone array (in my case a Voice HAT, connected to a Raspberry Pi via an I2S interface).

Something like...

`MozillaSpeechService.setInputDevice(device)`

where `device` is an `android.media.AudioDeviceInfo` object you can get from `android.media.AudioManager`.

See https://github.com/androidthings/sample-googleassistant/blob/master/app/src/main/java/com/example/androidthings/assistant/AssistantActivity.java#L179 for an example of what I mean.

From an implementation point of view, usually in Android that could then be set using `AudioRecord.setPreferredDevice(device)` but this may be complicated by the fact AudioRecord is currently done by a third party library (`com.github.axet.audiolibrary.encoders.Sound`) which doesn't appear to have any obvious way to specify an input device :(

**Comment by keianhzo** [comment]
@benfrancis Not in scopebut we accept PRs
