### ISSUE TITLE
Not accurate

### ISSUE THREAD

**Issue by chnouman** [mozilla/androidspeech#14]
I have tried to run it everything works fine but it the results are very disappointing it returns 
```
"helone" when I speak "hello"
"apl" for "apple"
"gobl" for "google"
```

Is there any way I can improve its accuracy by training model or something else?

**Comment by kdavis-mozilla** [comment]
What acoustic model are you using? Are you using a language model? Are you using the proper STT Android microphone settings?

**Comment by chnouman** [comment]
I simply run "androidspeech" project and have changed nothing.

**Comment by kdavis-mozilla** [comment]
What STT engine are you using?

**Comment by chnouman** [comment]
I'm using "mozillaspeechlibrary" dear.

on startButton this code is running:

               mMozillaSpeechService.addListener(this);
                mDtstart = System.currentTimeMillis();
                mSeries1.resetData(new DataPoint[0]);
                mMozillaSpeechService.setLanguage(txtLanguage.getText().toString());
                mMozillaSpeechService.setProductTag(txtProdutTag.getText().toString());
                mMozillaSpeechService.setModelPath(getExternalFilesDir("models").getAbsolutePath());
                mMozillaSpeechService.start(getApplicationContext());
                
the models files are also downloaded and placed to the correct location and unzipped.

**Comment by kdavis-mozilla** [comment]
"Dear"?

**Comment by chnouman** [comment]
it's nothing.

**Comment by chnouman** [comment]
@kdavis-mozilla is there any way I can improve its performance?

**Comment by lissyx** [comment]
> the models files are also downloaded and placed to the correct location and unzipped.

It's all not stable and not polished, old models, without language model, so it's kind of expected that it's not that accurate.

**Comment by lissyx** [comment]
@chnouman Also, english model 0.4.1 may still be very far from accurate with accents others than american english

**Comment by chnouman** [comment]
@lissyx thank you for the response. Do you know another Speech to Text library which has great accuracy other than Google STT? and works offline as well?

**Comment by lissyx** [comment]
> @lissyx thank you for the response. Do you know another Speech to Text library which has great accuracy other than Google STT? and works offline as well?

No, I would rather suggest you to reach to us on DeepSpeech's Github / Discourse, here is not the proper place. We just released a new 0.5.0 version. You may get even more accurate results with proper accent tuning.

**Comment by lissyx** [comment]
Also @chnouman I'd like to insist that DeepSpeech is still under heavy development, so feedback like this is good, and there's a lot of room for improvement. For example, you shared no mention of our device / system. We only tested on Google Pixel 2 and Sony Xperia XZ devices, getting much better results that those you report. But again, it might also depend a lot on the accent, since english model is really focusing on american english. Contributing to Common Voice with different accents (we need a lot of them) is likely a good way to help.

**Comment by keianhzo** [comment]
@lissyx should we keep this opened?

**Comment by lissyx** [comment]
No idea. There's nothing really actionable, no more feedback ...

**Comment by keianhzo** [comment]
Opened for too long and nothing actionable. Closing.
