### ISSUE TITLE
E/LocalDSInference: new DeepSpeechModel("null/eng/output_graph.tflite")

### ISSUE THREAD

**Issue by hackstock** [mozilla/androidspeech#29]
I have confirmed by browsing files on my external storage that all the necessary files are in there and yet running local inference fails. On my external storage I see the following files inside my application's folder: 
alphabet.txt
lm.binary
output_graph.tflite
trie

These files are located in com.pie.deepspeech/files/models/eng

**Comment by lissyx** [comment]
@hackstock Can you share STR ? Why does your title references `null/eng/` path ? Have you granted device storage permissions ?

**Comment by keianhzo** [comment]
@hackstock is this still actionable after the 2.0.0 update? can you please update/close otherwise?
