### ISSUE TITLE
Audio file

### ISSUE THREAD

**Issue by buzynski** [mozilla/androidspeech#35]
Hi,

how can i get recorded audio file ?

Why instead of null, you can't pass byteArray here ?
```
 public void onStart() {
                        // called before request is started
                        mSpeechService.notifyListeners(MozillaSpeechService.SpeechState.DECODING, null);
                    }
```

Thanks in advance !

**Comment by keianhzo** [comment]
@buzynski The has been a refactor that affected this issue. Can you please review and update/close? Thanks!
