### ISSUE TITLE
AndroidSpeechLibrary - Http Error 400

### ISSUE THREAD

**Issue by MuhammadRashid** [mozilla/androidspeech#39]
Hi,
I am always getting sttp error when I run the demo app from android speech. I am playing video/audio in background with English language to get live transcribe.

After debugging I found that it gives HTTP Error 400 on a network request for audio transcription to Mozilla Speech Service.

I am using following configurations to call speech service:
 SpeechServiceSettings.Builder builder = new SpeechServiceSettings.Builder()
                    .withLanguage("en-US")
                    .withStoreSamples(false)
                    .withStoreTranscriptions(false)
                    .withProductTag("product-tag")
                    .withUseDeepSpeech(false);                    
            mSpeechService.start(builder.build(), mVoiceSearchListener);

I have attached screenshot for more details.

![online_sttp_error](https://user-images.githubusercontent.com/10269811/84118541-927b1e00-aa4c-11ea-9a9b-4a531c287fb1.png)

**Comment by keianhzo** [comment]
There has been some server side change and now an empty product tag is not accepted anymore. We are going to push an update to fix this.

**Comment by MuhammadRashid** [comment]
Thank you very much @keianhzo for your kind response. Looking forward to the fix.

**Comment by MuhammadRashid** [comment]
> There has been some server side change and now an empty product tag is not accepted anymore. We are going to push an update to fix this.

Hi @keianhzo, would you like to tell when can I expect the fix. Actually, I really need that fix. Thank you.

**Comment by keianhzo** [comment]
@keianhzo We are waiting for information to work on this, we will update as soon as possible.

**Comment by MuhammadRashid** [comment]
> @keianhzo We are waiting for information to work on this, we will update as soon as possible.

Thank you for this update.

**Comment by keianhzo** [comment]
@MuhammadRashid The support for http requests without product tag has been removed int he backend. Now you always need to provide a product tag to make http requests using the demo app.

**Comment by MuhammadRashid** [comment]
> @MuhammadRashid The support for http requests without product tag has been removed int he backend. Now you always need to provide a product tag to make http requests using the demo app.

@keianhzo thank you very much for this update. Can you please give some details about product tag? What is it actually? And what it product tag value will be required to provide during http request? Kindly ignore my ignorance. I am new to use Mozilla Speech for Android here.

**Comment by MuhammadRashid** [comment]
> @MuhammadRashid The support for http requests without product tag has been removed int he backend. Now you always need to provide a product tag to make http requests using the demo app.

Hi @keianhzo, issue still exists. 
With demo app, I used the following configuration to make a http request;
 SpeechServiceSettings.Builder builder = new SpeechServiceSettings.Builder()
                    .withLanguage(mTxtLanguage.getText().toString())
                    .withStoreSamples(mStoreSamplesSwitch.isChecked())
                    .withStoreTranscriptions(mTranscriptionsSwitch.isChecked())
                    .withProductTag(txtProductTag.getText().toString())
                    .withUseDeepSpeech(mDeepSpeechSwitch.isChecked());

For product tag, I tried with different values i.e "product tag", "product-tag", "androidspeech" and "moz-android-speech-lib" etc but getting same **HTTP 400** error in response. 

Please see attach screenshot for more details;
![http-400-error](https://user-images.githubusercontent.com/10269811/84763387-88759400-afe5-11ea-81dc-f514b0af1878.png)
