### ISSUE TITLE
Update libdeepspeech & model to v0.7.3

### ISSUE THREAD

**Issue by keianhzo** [mozilla/androidspeech#41]

**Comment by MuhammadRashid** [comment]
Hi @keianhzo, thanks a lot for initiating it. When we can expect this updated model?

**Comment by kdavis-mozilla** [comment]
The model has been [released](https://github.com/mozilla/DeepSpeech/releases/tag/v0.7.3), the integration work here is not done.

**Comment by MuhammadRashid** [comment]
> The model has been [released](https://github.com/mozilla/DeepSpeech/releases/tag/v0.7.3), the integration work here is not done.

@kdavis-mozilla, thank you for this info. I am sorry for my ignorance. Actually, I am new to using the Mozilla Android Speech Library for audio transcription from an audio source. Before I have used the Google Speech to Text API and now I want to understand and use Mozilla's Android Speech Library in my app. I am successfully getting continuous speech recognititon by using existing model files after changing source code of demo app. It gives me a good accuracy but for more better accuracy I am looking for latest model files that may be v0.7.3 or v0.8.0-alpha.3.

I am playing with the latest [androidspeech library and demo app](https://github.com/mozilla/androidspeech). It downloads the en-us.zip with v0.6.0. I am considering about the update of following files for v0.7.3 for better transcription accuracy than v0.6.0;
1. output_graph.tflite
2. info.json
3. Im.binary
4. trie

Please see the screenshot below about those files;
![model_files](https://user-images.githubusercontent.com/10269811/84403290-fb19f480-ac1e-11ea-9d01-da3cb489f6ab.png)

Please clarify me when you say "the integration work here is not done." means those files are not ready yet to available for download and use with androidspeech library. Or it is a different context that I am not familiar with. 

On this link https://github.com/mozilla/DeepSpeech/tags, I also found v0.8.0-alpha.3. 

When can I expect updated/latest version of above model files above v0.6.0?

**Comment by kdavis-mozilla** [comment]
The 0.7.3 model has been [released](https://github.com/mozilla/DeepSpeech/releases/tag/v0.7.3), the integration work here is not done.

**Comment by MuhammadRashid** [comment]
> The 0.7.3 model has been [released](https://github.com/mozilla/DeepSpeech/releases/tag/v0.7.3), the integration work here is not done.

Okay, thank you. Can you please let us know when integration part will be done?

**Comment by kdavis-mozilla** [comment]
That's the goal of this issue. So just continue to follow updates here.
