### ISSUE TITLE
Product Tag and its usage 

### ISSUE THREAD

**Issue by MuhammadRashid** [mozilla/androidspeech#42]
Hi,
Can anybody please provide some useful info about product tag and its usage in speech service settings to use Mozilla Speech Service? I searched in Wiki docs and overall on different forums but found nothing about product tag and its usage. 

With demo app, I used the following SpeechServiceSettings to make a http request to https://speaktome-2.services.mozilla.com/ for speech recognition.
SpeechServiceSettings.Builder builder = new SpeechServiceSettings.Builder()
.withLanguage("en-us")
.withStoreSamples(false)
.withStoreTranscriptions(false)
.withProductTag("product tag")
.withUseDeepSpeech(false);

For product tag, I tried with unique values i.e. "product tag", "product-tag", "androidspeech" and "moz-android-speech-lib" etc but getting same HTTP 400 error in response.

**Comment by DarkSherlock** [comment]
I got the same issue
