### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by vishwakneelamegam** [mozilla/androidspeech#50]
when i add this 'com.github.mozilla:mozillaspeechutils:2.0.0' to my gradle error occurs.
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find androidspeech:mozillaspeechlibrary:unspecified.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/androidspeech/mozillaspeechlibrary/unspecified/mozillaspeechlibrary-unspecified.pom
       - https://jcenter.bintray.com/androidspeech/mozillaspeechlibrary/unspecified/mozillaspeechlibrary-unspecified.pom
     Required by:
         project :app > com.github.mozilla:mozillaspeechutils:2.0.0

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

**Comment by vishwakneelamegam** [comment]
i have used org.deepspeech:libdeepspeech:0.9.3 this gradle and it's working nice.  To see my code use this link https://github.com/vishwakneelamegam/deepspeech-android.  Thank you.

**Comment by windmaple** [comment]
I met the same error with https://github.com/mozilla/DeepSpeech-examples/android-mic-streaming. Not sure how to resolve it

**Comment by vishwakneelamegam** [comment]
> I met the same error with https://github.com/mozilla/DeepSpeech-examples/android-mic-streaming. Not sure how to resolve it

i have used org.deepspeech:libdeepspeech:0.9.3 this gradle and it's working nice. To see my code use this link https://github.com/vishwakneelamegam/deepspeech-android. Thank you.
